apiVersion: v1
kind: Secret
metadata:
  name: progettotest
type: Opaque
data:
  # Base64 encoded values
  # In un vero scenario, questi sarebbero valori sensibili (password DB, API keys, ecc.)
  # Per questo esercizio, usiamo stringhe di esempio codificate in base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BkYjo1NDMyL25vbWVkYg==
  